User tinyproxy
Group tinyproxy
Port 3128
Listen 0.0.0.0
Timeout 600
LogFile "/dev/stdout"
LogLevel Info
PidFile "/tmp/tinyproxy.pid"
MaxClients 50
Allow 0.0.0.0/0
ConnectPort 443
Filter "/etc/tinyproxy/filter"
FilterDefaultDeny Yes
FilterURLs On
DisableViaHeader Yes
