import React, { useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Alert, App as AntApp, Badge, Button, Card, Col, ConfigProvider, Descriptions, Empty, Form, Input, Layout, Menu, Modal, Row, Select, Space, Spin, Statistic, Table, Tag, Typography, message } from 'antd'
import { AuditOutlined, CheckCircleOutlined, DashboardOutlined, FileTextOutlined, HddOutlined, LinkOutlined, LogoutOutlined, RobotOutlined, SafetyCertificateOutlined, SendOutlined, TeamOutlined, UsergroupAddOutlined } from '@ant-design/icons'
import 'antd/dist/reset.css'
import './styles.css'

const { Header, Sider, Content } = Layout
const queryClient = new QueryClient()

type Json = Record<string, any>
const roleLabel: Record<string,string> = {'DROLE-01':'PMA 产品营销','DROLE-02':'BGA 品牌增长','DROLE-03':'MO 营销协同'}
const statusColor: Record<string,string> = {proposed:'blue',accepted:'cyan',active:'green',waiting:'orange',submitted:'purple',fulfilled:'green',paused:'red',manual_takeover:'volcano'}

function token() { return localStorage.getItem('1cat_token') || '' }
async function api(path:string, options:RequestInit={}) {
  const headers = new Headers(options.headers)
  headers.set('Content-Type','application/json')
  if (token()) headers.set('Authorization',`Bearer ${token()}`)
  if (options.method && options.method !== 'GET') {
    const id = crypto.randomUUID()
    headers.set('X-Correlation-ID',id)
    headers.set('Idempotency-Key',id)
  }
  const result = await fetch(path,{...options,headers})
  if (result.status===401) { localStorage.removeItem('1cat_token'); throw new Error('登录已失效') }
  if (!result.ok) { const body=await result.json().catch(()=>({})); throw new Error(body.detail||`请求失败 ${result.status}`) }
  return result.json()
}

function Login({onLogin}:{onLogin:()=>void}) {
  const [busy,setBusy]=useState(false)
  async function submit(values:{username:string,password:string}) {
    setBusy(true)
    try {
      const data=new URLSearchParams({grant_type:'password',client_id:'1cat-workspace',username:values.username,password:values.password})
      const response=await fetch('/auth/realms/1cat/protocol/openid-connect/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:data})
      if(!response.ok) throw new Error('用户名或密码不正确')
      const result=await response.json(); localStorage.setItem('1cat_token',result.access_token); onLogin()
    } catch(e:any) { message.error(e.message) } finally { setBusy(false) }
  }
  return <div className="login-shell"><div className="login-visual"><div className="cat-mark">1CAT</div><h1>把营销团队变成<br/>可协作的数字组织</h1><p>三个数字岗位在清晰权限、人工批准和完整证据链中协作。</p><div className="guardrails"><span>四平台人工发布</span><span>PII关闭</span><span>全程可接管</span></div></div><Card className="login-card" bordered={false}><Typography.Title level={2}>进入组织工作台</Typography.Title><Typography.Paragraph type="secondary">使用个人身份登录，所有操作都会留下审计记录。</Typography.Paragraph><Form layout="vertical" onFinish={submit} initialValues={{username:'admin'}}><Form.Item label="用户名" name="username" rules={[{required:true}]}><Input size="large"/></Form.Item><Form.Item label="密码" name="password" rules={[{required:true}]}><Input.Password size="large" placeholder="请输入初始化生成的首次登录密码"/></Form.Item><Button size="large" type="primary" htmlType="submit" block loading={busy}>安全登录</Button></Form></Card></div>
}

function Dashboard() {
  const roles=useQuery({queryKey:['roles'],queryFn:()=>api('/v1/roles')})
  const commitments=useQuery({queryKey:['commitments'],queryFn:()=>api('/v1/commitments')})
  const runs=useQuery({queryKey:['runs'],queryFn:()=>api('/v1/runs'),refetchInterval:3000})
  const tasks=useQuery({queryKey:['tasks'],queryFn:()=>api('/v1/manual-tasks')})
  if(roles.isLoading) return <Spin/>
  return <Space direction="vertical" size={20} style={{width:'100%'}}><div><Typography.Title level={2}>组织运行总览</Typography.Title><Typography.Text type="secondary">今天的责任、等待和人工动作都在这里。</Typography.Text></div><Alert showIcon type="info" message="R0安全运行中" description="抖音、小红书、B站、公众号均为人工发布；视频号休眠；真实PII关闭。"/><Row gutter={[16,16]}><Col xs={12} lg={6}><Card><Statistic title="数字岗位" value={roles.data?.length||0} suffix="个" prefix={<RobotOutlined/>}/></Card></Col><Col xs={12} lg={6}><Card><Statistic title="进行中承诺" value={(commitments.data||[]).filter((x:Json)=>!['fulfilled','cancelled','rejected'].includes(x.status)).length} suffix="项"/></Card></Col><Col xs={12} lg={6}><Card><Statistic title="Agent运行" value={runs.data?.length||0} suffix="次"/></Card></Col><Col xs={12} lg={6}><Card><Statistic title="待人工任务" value={(tasks.data||[]).filter((x:Json)=>x.status==='pending').length} suffix="项"/></Card></Col></Row><Row gutter={[16,16]}>{(roles.data||[]).map((role:Json)=><Col xs={24} lg={8} key={role.id}><Card className="role-card"><Space align="start"><div className={`role-dot ${role.profile_id}`}>{role.profile_id.toUpperCase()}</div><div><Typography.Title level={4}>{role.name}</Typography.Title><Tag color="processing">{role.lifecycle}</Tag><Typography.Paragraph type="secondary">业务Owner：{role.owner_role}</Typography.Paragraph></div></Space></Card></Col>)}</Row></Space>
}

function Commitments() {
  const qc=useQueryClient(); const [open,setOpen]=useState(false)
  const query=useQuery({queryKey:['commitments'],queryFn:()=>api('/v1/commitments')})
  const create=useMutation({mutationFn:(v:Json)=>api('/v1/commitments',{method:'POST',body:JSON.stringify({...v,acceptance:{requires_human_acceptance:true},dependencies:[],context:{pii:false}})}),onSuccess:()=>{message.success('已创建协作承诺');setOpen(false);qc.invalidateQueries({queryKey:['commitments']})},onError:(e:any)=>message.error(e.message)})
  const transition=useMutation({mutationFn:({id,status}:Json)=>api(`/v1/commitments/${id}/transition`,{method:'POST',body:JSON.stringify({status,reason:'由具名人类在工作台确认'})}),onSuccess:()=>{message.success('状态已更新');qc.invalidateQueries({queryKey:['commitments']})},onError:(e:any)=>message.error(e.message)})
  const actions:Record<string,{label:string,status:string,danger?:boolean}[]>={proposed:[{label:'接受',status:'accepted'}],accepted:[{label:'启动',status:'active'},{label:'暂停',status:'paused',danger:true}],active:[{label:'暂停',status:'paused',danger:true},{label:'人工接管',status:'manual_takeover',danger:true}],waiting:[{label:'恢复',status:'active'},{label:'人工接管',status:'manual_takeover',danger:true}],submitted:[{label:'确认完成',status:'fulfilled'}],paused:[{label:'恢复',status:'active'}],manual_takeover:[{label:'送审',status:'submitted'}]}
  const columns=[{title:'承诺',dataIndex:'title',render:(v:string,r:Json)=><><b>{v}</b><div className="muted">{r.objective}</div></>},{title:'责任岗位',dataIndex:'proposed_role',render:(v:string)=>roleLabel[v]||v},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={statusColor[v]}>{v}</Tag>},{title:'版本',dataIndex:'version',width:80},{title:'人工决定',render:(_:any,r:Json)=><Space wrap>{(actions[r.status]||[]).map(a=><Button key={a.status} size="small" danger={a.danger} onClick={()=>transition.mutate({id:r.id,status:a.status})}>{a.label}</Button>)}</Space>}]
  return <Page title="协作承诺" subtitle="ORS-03是唯一事实源；卡片和Agent运行不能直接改变业务完成状态。" action={<Button type="primary" onClick={()=>setOpen(true)}>新建承诺</Button>}><Table rowKey="id" loading={query.isLoading} dataSource={query.data||[]} columns={columns}/><Modal title="新建协作承诺" open={open} footer={null} onCancel={()=>setOpen(false)}><Form layout="vertical" onFinish={v=>create.mutate(v)}><Form.Item name="title" label="事项名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="proposed_role" label="建议责任岗位" rules={[{required:true}]}><Select options={Object.entries(roleLabel).map(([value,label])=>({value,label}))}/></Form.Item><Form.Item name="objective" label="期望结果" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>提交协商</Button></Form></Modal></Page>
}

function Runs() {
  const qc=useQueryClient(); const [open,setOpen]=useState(false)
  const runs=useQuery({queryKey:['runs'],queryFn:()=>api('/v1/runs'),refetchInterval:2500})
  const commitments=useQuery({queryKey:['commitments'],queryFn:()=>api('/v1/commitments')})
  const create=useMutation({mutationFn:(v:Json)=>api('/v1/runs',{method:'POST',body:JSON.stringify({...v,context_version:1})}),onSuccess:()=>{message.success('已进入运行队列');setOpen(false);qc.invalidateQueries({queryKey:['runs']})},onError:(e:any)=>message.error(e.message)})
  return <Page title="Agent运行" subtitle="每次运行都绑定岗位、Profile、Commitment与证据；运行成功只代表已提交候选结果。" action={<Button type="primary" icon={<SendOutlined/>} onClick={()=>setOpen(true)}>启动Agent</Button>}><Table rowKey="id" dataSource={runs.data||[]} loading={runs.isLoading} columns={[{title:'岗位',dataIndex:'role_id',render:(v:string)=>roleLabel[v]||v},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={v==='unknown'?'red':statusColor[v]||'blue'}>{v}</Tag>},{title:'输入',dataIndex:'input_text',ellipsis:true},{title:'结果',dataIndex:'output',render:(v:Json)=><span className="muted">{v?.message||v?.candidate_status||'—'}</span>},{title:'创建时间',dataIndex:'created_at',render:(v:string)=>new Date(v).toLocaleString()}]}/><Modal title="启动有界Agent运行" open={open} footer={null} onCancel={()=>setOpen(false)}><Form layout="vertical" onFinish={v=>create.mutate(v)}><Form.Item name="commitment_id" label="已接受的Commitment" rules={[{required:true}]}><Select options={(commitments.data||[]).filter((x:Json)=>['accepted','active'].includes(x.status)).map((x:Json)=>({value:x.id,label:x.title}))}/></Form.Item><Form.Item name="role_id" label="岗位" rules={[{required:true}]}><Select options={Object.entries(roleLabel).map(([value,label])=>({value,label}))}/></Form.Item><Form.Item name="input" label="任务说明" rules={[{required:true}]}><Input.TextArea rows={5}/></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>确认启动</Button></Form></Modal></Page>
}

function Knowledge() {
  const qc=useQueryClient(); const [open,setOpen]=useState(false)
  const q=useQuery({queryKey:['knowledge'],queryFn:()=>api('/v1/knowledge')})
  const create=useMutation({mutationFn:(v:Json)=>api('/v1/knowledge',{method:'POST',body:JSON.stringify({...v,source_refs:(v.source_refs||'synthetic://workspace').split(/[,\n]/).map((x:string)=>x.trim()).filter(Boolean),metadata:{created_in_workspace:true}})}),onSuccess:()=>{message.success('候选已保存');setOpen(false);qc.invalidateQueries({queryKey:['knowledge']})},onError:(e:any)=>message.error(e.message)})
  const kinds=[['brief','Brief'],['evidence','证据'],['fact','产品事实候选'],['claim','Claim候选'],['campaign','Campaign候选'],['content','内容母稿/平台候选'],['review','复盘候选']].map(([value,label])=>({value,label}))
  return <Page title="Brief、产品事实与内容资产" subtitle="所有对象默认是候选；正式Fact、Claim和业务决定必须由具名人类批准。" action={<Button type="primary" onClick={()=>setOpen(true)}>新建候选</Button>}><Table rowKey="id" dataSource={q.data||[]} loading={q.isLoading} locale={{emptyText:<Empty description="尚无知识资产"/>}} columns={[{title:'类型',dataIndex:'kind',render:(v:string)=><Tag>{v}</Tag>},{title:'标题',dataIndex:'title'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color="blue">{v}</Tag>},{title:'来源',dataIndex:'source_refs',render:(v:string[])=>(v||[]).length+'个'},{title:'版本',dataIndex:'version'}]}/><Modal title="新建业务候选" open={open} footer={null} onCancel={()=>setOpen(false)}><Form layout="vertical" onFinish={v=>create.mutate(v)}><Form.Item name="kind" label="对象类型" rules={[{required:true}]}><Select options={kinds}/></Form.Item><Form.Item name="title" label="标题" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="body" label="内容" rules={[{required:true}]}><Input.TextArea rows={6} placeholder="禁止输入真实手机号、邮箱或客户明文信息"/></Form.Item><Form.Item name="source_refs" label="SourceRef（逗号或换行分隔）"><Input.TextArea rows={2}/></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>保存候选</Button></Form></Modal></Page>
}

function ManualTasks() {
  const qc=useQueryClient(); const [open,setOpen]=useState(false); const [receipt,setReceipt]=useState<Json|null>(null)
  const q=useQuery({queryKey:['tasks'],queryFn:()=>api('/v1/manual-tasks')})
  const create=useMutation({mutationFn:(v:Json)=>api('/v1/manual-tasks',{method:'POST',body:JSON.stringify({...v,task_type:'publish',object_ref:{id:v.object_id,version:Number(v.object_version||1)}})}),onSuccess:()=>{message.success('人工任务已创建');setOpen(false);qc.invalidateQueries({queryKey:['tasks']})},onError:(e:any)=>message.error(e.message)})
  const record=useMutation({mutationFn:(v:Json)=>api(`/v1/manual-tasks/${receipt?.id}/receipt`,{method:'POST',headers:{'If-Match':String(receipt?.version)},body:JSON.stringify({status:v.status,receipt:{note:v.note,recorded_by_human:true}})}),onSuccess:()=>{message.success('人工回执已记录');setReceipt(null);qc.invalidateQueries({queryKey:['tasks']})},onError:(e:any)=>message.error(e.message)})
  return <Page title="人工发布与接管" subtitle="系统只准备不可变任务；登录平台、发布、私信和外联始终由具名人类完成。" action={<Button type="primary" onClick={()=>setOpen(true)}>新建人工发布任务</Button>}><Alert className="section-alert" showIcon type="warning" message="没有任何平台自动写入能力；视频号不在可选列表"/><Table rowKey="id" dataSource={q.data||[]} loading={q.isLoading} columns={[{title:'平台',dataIndex:'platform',render:(v:string)=><Tag color="geekblue">{v}</Tag>},{title:'任务',dataIndex:'task_type'},{title:'状态',dataIndex:'status',render:(v:string)=><Badge status={v==='pending'?'processing':v==='completed'?'success':'warning'} text={v}/>},{title:'操作说明',dataIndex:'instructions'},{title:'负责人',dataIndex:'assigned_to',render:(v:string)=>v||'待分配'},{title:'人工动作',render:(_:any,r:Json)=>r.status==='pending'?<Button size="small" onClick={()=>setReceipt(r)}>记录回执</Button>:'—'}]}/><Modal title="新建人工发布任务" open={open} footer={null} onCancel={()=>setOpen(false)}><Form layout="vertical" onFinish={v=>create.mutate(v)} initialValues={{object_version:1}}><Form.Item name="platform" label="平台" rules={[{required:true}]}><Select options={[['douyin','抖音'],['xiaohongshu','小红书'],['bilibili','B站'],['wechat_official','公众号']].map(([value,label])=>({value,label}))}/></Form.Item><Form.Item name="object_id" label="已审核候选对象ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="object_version" label="对象版本" rules={[{required:true}]}><Input type="number"/></Form.Item><Form.Item name="instructions" label="人工操作说明" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item><Form.Item name="assigned_to" label="具名负责人"><Input/></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>创建任务</Button></Form></Modal><Modal title="记录人工回执" open={Boolean(receipt)} footer={null} onCancel={()=>setReceipt(null)}><Alert showIcon type="info" message="只记录实际观察结果；无法确认时选择 unknown，不得伪造发布成功。"/><Form layout="vertical" onFinish={v=>record.mutate(v)}><Form.Item name="status" label="结果" rules={[{required:true}]}><Select options={[{value:'completed',label:'已由人类完成'},{value:'failed',label:'执行失败'},{value:'unknown',label:'结果未知'}]}/></Form.Item><Form.Item name="note" label="回执说明" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item><Button type="primary" htmlType="submit">确认记录</Button></Form></Modal></Page>
}

function Leads() {
  const qc=useQueryClient(); const [open,setOpen]=useState(false); const [feedback,setFeedback]=useState<Json|null>(null)
  const leads=useQuery({queryKey:['leads'],queryFn:()=>api('/v1/leads')}); const feedbacks=useQuery({queryKey:['sales-feedback'],queryFn:()=>api('/v1/sales-feedback')})
  const create=useMutation({mutationFn:(v:Json)=>api('/v1/leads',{method:'POST',body:JSON.stringify(v)}),onSuccess:()=>{message.success('LeadStub已登记');setOpen(false);qc.invalidateQueries({queryKey:['leads']})},onError:(e:any)=>message.error(e.message)})
  const record=useMutation({mutationFn:(v:Json)=>api('/v1/sales-feedback',{method:'POST',body:JSON.stringify({...v,lead_stub_id:feedback?.id,lead_version:feedback?.version})}),onSuccess:()=>{message.success('销售反馈已记录');setFeedback(null);qc.invalidateQueries({queryKey:['sales-feedback']})},onError:(e:any)=>message.error(e.message)})
  const latest=(id:string)=>(feedbacks.data||[]).find((x:Json)=>x.lead_stub_id===id)
  return <Page title="LeadStub与销售反馈" subtitle="这里只保存不透明来源引用；姓名、手机、邮箱、私信正文均禁止进入R0。" action={<Button type="primary" onClick={()=>setOpen(true)}>登记LeadStub</Button>}><Alert showIcon type="info" message="询盘四状态只能由具名销售人类写入，Agent只能读取明确反馈。"/><Table rowKey="id" dataSource={leads.data||[]} loading={leads.isLoading} columns={[{title:'来源引用',dataIndex:'source_record_ref'},{title:'触点',dataIndex:'touchpoint'},{title:'Campaign',dataIndex:'campaign_ref',render:(v:string)=>v||'—'},{title:'销售反馈',render:(_:any,r:Json)=>latest(r.id)?<Tag color="purple">{latest(r.id).inquiry_status}</Tag>:<Tag>未反馈</Tag>},{title:'人工动作',render:(_:any,r:Json)=><Button size="small" onClick={()=>setFeedback(r)}>销售反馈</Button>}]}/><Modal title="登记PII-free LeadStub" open={open} footer={null} onCancel={()=>setOpen(false)}><Form layout="vertical" onFinish={v=>create.mutate(v)}><Form.Item name="source_record_ref" label="不透明来源引用" rules={[{required:true}]}><Input placeholder="例如 crm://stub/opaque-id；不得填姓名或联系方式"/></Form.Item><Form.Item name="touchpoint" label="来源触点" rules={[{required:true}]}><Input placeholder="例如 douyin-comment"/></Form.Item><Form.Item name="campaign_ref" label="Campaign引用"><Input/></Form.Item><Form.Item name="content_ref" label="Content引用"><Input/></Form.Item><Button type="primary" htmlType="submit">安全登记</Button></Form></Modal><Modal title="记录销售人类反馈" open={Boolean(feedback)} footer={null} onCancel={()=>setFeedback(null)}><Form layout="vertical" onFinish={v=>record.mutate(v)}><Form.Item name="inquiry_status" label="销售判断" rules={[{required:true}]}><Select options={['pending','valid','invalid','needs_more_info'].map(value=>({value,label:value}))}/></Form.Item><Form.Item name="reason_code" label="原因码" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="registry_version" label="原因码注册表版本" rules={[{required:true}]}><Input/></Form.Item><Button type="primary" htmlType="submit">以当前销售身份记录</Button></Form></Modal></Page>
}

function Collaboration() {
  const qc=useQueryClient(); const [handoffOpen,setHandoffOpen]=useState(false); const [approvalOpen,setApprovalOpen]=useState(false)
  const handoffs=useQuery({queryKey:['handoffs'],queryFn:()=>api('/v1/handoffs')}); const approvals=useQuery({queryKey:['approvals'],queryFn:()=>api('/v1/approvals')}); const commitments=useQuery({queryKey:['commitments'],queryFn:()=>api('/v1/commitments')})
  const handoff=useMutation({mutationFn:(v:Json)=>api('/v1/handoffs',{method:'POST',body:JSON.stringify({...v,payload:{prepared_in_workspace:true}})}),onSuccess:()=>{message.success('交接已创建');setHandoffOpen(false);qc.invalidateQueries({queryKey:['handoffs']})},onError:(e:any)=>message.error(e.message)})
  const approval=useMutation({mutationFn:(v:Json)=>api('/v1/approvals',{method:'POST',body:JSON.stringify({...v,subject_version:Number(v.subject_version),scope:{r0:true,external_write:false}})}),onSuccess:()=>{message.success('ApprovalGrant已签发');setApprovalOpen(false);qc.invalidateQueries({queryKey:['approvals']})},onError:(e:any)=>message.error(e.message)})
  return <Page title="岗位交接与人工批准" subtitle="交接发送不等于接收；批准只对具体对象、版本和动作生效。" action={<Space><Button onClick={()=>setHandoffOpen(true)}>新建交接</Button><Button type="primary" onClick={()=>setApprovalOpen(true)}>签发批准</Button></Space>}><Row gutter={[16,16]}><Col span={24}><Card title="岗位交接"><Table size="small" rowKey="id" dataSource={handoffs.data||[]} columns={[{title:'Commitment',dataIndex:'commitment_id'},{title:'发送岗位',dataIndex:'sender_role',render:(v:string)=>roleLabel[v]||v},{title:'接收者',dataIndex:'recipient'},{title:'目的',dataIndex:'purpose'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag>{v}</Tag>} ]}/></Card></Col><Col span={24}><Card title="ApprovalGrant"><Table size="small" rowKey="id" dataSource={approvals.data||[]} columns={[{title:'对象',render:(_:any,r:Json)=>`${r.subject_type}/${r.subject_id}@${r.subject_version}`},{title:'动作',dataIndex:'action'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color="green">{v}</Tag>},{title:'签发人',dataIndex:'issued_by'},{title:'剩余次数',dataIndex:'remaining_uses'}]}/></Card></Col></Row><Modal title="新建岗位交接" open={handoffOpen} footer={null} onCancel={()=>setHandoffOpen(false)}><Form layout="vertical" onFinish={v=>handoff.mutate(v)}><Form.Item name="commitment_id" label="Commitment" rules={[{required:true}]}><Select options={(commitments.data||[]).map((x:Json)=>({value:x.id,label:x.title}))}/></Form.Item><Form.Item name="sender_role" label="发送岗位" rules={[{required:true}]}><Select options={Object.entries(roleLabel).map(([value,label])=>({value,label}))}/></Form.Item><Form.Item name="recipient" label="接收人或岗位" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="purpose" label="交接目的" rules={[{required:true}]}><Input.TextArea rows={3}/></Form.Item><Button type="primary" htmlType="submit">创建交接</Button></Form></Modal><Modal title="签发对象级ApprovalGrant" open={approvalOpen} footer={null} onCancel={()=>setApprovalOpen(false)}><Form layout="vertical" onFinish={v=>approval.mutate(v)} initialValues={{subject_version:1}}><Form.Item name="subject_type" label="对象类型" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="subject_id" label="对象ID" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="subject_version" label="对象版本" rules={[{required:true}]}><Input type="number"/></Form.Item><Form.Item name="action" label="批准动作" rules={[{required:true}]}><Input placeholder="例如 submit_review；不支持平台自动发布"/></Form.Item><Button type="primary" htmlType="submit">确认签发</Button></Form></Modal></Page>
}
function Audit() { const q=useQuery({queryKey:['audit'],queryFn:()=>api('/v1/audit')}); return <Page title="审计与证据" subtitle="每次写入、授权、拒绝、Agent运行和人工动作均以correlation ID关联。"><Table rowKey="id" size="small" dataSource={q.data||[]} loading={q.isLoading} columns={[{title:'时间',dataIndex:'created_at',render:(v:string)=>new Date(v).toLocaleString()},{title:'Actor',dataIndex:'actor_id'},{title:'动作',dataIndex:'action'},{title:'对象',render:(_:any,r:Json)=>`${r.resource_type}/${r.resource_id}`},{title:'决定',dataIndex:'decision',render:(v:string)=><Tag color={v==='allow'?'green':'red'}>{v}</Tag>},{title:'关联ID',dataIndex:'correlation_id',ellipsis:true}]}/></Page> }
function Roles() { const q=useQuery({queryKey:['roles'],queryFn:()=>api('/v1/roles')}); return <Page title="三个数字岗位" subtitle="Profile是长期岗位运行单元，但真正的权限由服务身份和Policy Gateway控制。"><Row gutter={[16,16]}>{(q.data||[]).map((r:Json)=><Col span={24} key={r.id}><Card><Descriptions title={`${r.name} · ${r.id}`} column={{xs:1,md:3}} items={[{key:'profile',label:'Profile',children:r.profile_id},{key:'owner',label:'业务Owner',children:r.owner_role},{key:'life',label:'生命周期',children:<Tag>{r.lifecycle}</Tag>},{key:'boundary',label:'R0边界',children:'候选、协作、人工审核；无外部平台写',span:3}]}/></Card></Col>)}</Row></Page> }

function Page({title,subtitle,action,children}:{title:string,subtitle:string,action?:React.ReactNode,children:React.ReactNode}) { return <Space direction="vertical" size={18} style={{width:'100%'}}><div className="page-head"><div><Typography.Title level={2}>{title}</Typography.Title><Typography.Text type="secondary">{subtitle}</Typography.Text></div>{action}</div>{children}</Space> }

function Workspace({logout}:{logout:()=>void}) {
  const [selected,setSelected]=useState('dashboard')
  const page:Record<string,React.ReactNode>={dashboard:<Dashboard/>,roles:<Roles/>,commitments:<Commitments/>,runs:<Runs/>,knowledge:<Knowledge/>,collaboration:<Collaboration/>,tasks:<ManualTasks/>,leads:<Leads/>,audit:<Audit/>}
  return <Layout className="workspace"><Sider width={248} className="sider"><div className="brand"><div className="brand-icon">1C</div><div><b>1Cat Hermes OS</b><small>一猫营销组织运行台</small></div></div><Menu theme="dark" mode="inline" selectedKeys={[selected]} onSelect={({key})=>setSelected(key)} items={[{key:'dashboard',icon:<DashboardOutlined/>,label:'运行总览'},{key:'roles',icon:<TeamOutlined/>,label:'数字岗位'},{key:'commitments',icon:<CheckCircleOutlined/>,label:'协作承诺'},{key:'runs',icon:<RobotOutlined/>,label:'Agent运行'},{key:'knowledge',icon:<FileTextOutlined/>,label:'Brief与业务候选'},{key:'collaboration',icon:<LinkOutlined/>,label:'交接与批准'},{key:'tasks',icon:<HddOutlined/>,label:'人工任务'},{key:'leads',icon:<UsergroupAddOutlined/>,label:'Lead与销售反馈'},{key:'audit',icon:<AuditOutlined/>,label:'审计与证据'}]}/><div className="safety"><SafetyCertificateOutlined/><div><b>R0 安全边界</b><small>MANUAL · NO PII</small></div></div></Sider><Layout><Header className="topbar"><div><Badge status="success"/> 组织Runtime运行中</div><Button type="text" icon={<LogoutOutlined/>} onClick={logout}>退出</Button></Header><Content className="content">{page[selected]}</Content></Layout></Layout>
}

function Root() { const [logged,setLogged]=useState(Boolean(token())); return <ConfigProvider theme={{token:{colorPrimary:'#0d7c86',borderRadius:10,colorBgLayout:'#f4f7f8',fontFamily:'Inter, PingFang SC, Microsoft YaHei, sans-serif'}}}><AntApp>{logged?<Workspace logout={()=>{localStorage.removeItem('1cat_token');setLogged(false)}}/>:<Login onLogin={()=>setLogged(true)}/>}</AntApp></ConfigProvider> }
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><Root/></QueryClientProvider></React.StrictMode>)
